### POST 获取验证码
POST http://localhost:8081/user/code?phone=13889343526


### POST 使用验证码登录
POST http://localhost:8081/user/login
Content-Type: application/json

{
  "phone": "13889343526",
  "code": "630689",
  "password": ""
}

### GET 访问主页
GET http://localhost:8081/user/me
authorization: fec80389660846e8949f2388e69c935b

